### ISSUE TITLE
Unable to build consort-panel on Ubuntu Quantal and later

### ISSUE THREAD

**Issue by develop7** [SolusOS-discontinued/consort-panel#1]
According to [build log](https://launchpadlibrarian.net/129677970/buildlog_ubuntu-quantal-i386.consort-panel_1.0.1-0~29-1~quantal1_FAILEDTOBUILD.txt.gz), this is caused by [changed file layout](http://packages.ubuntu.com/quantal/amd64/libdconf-dev/filelist) and probably interface of dconf-panel. 

Any chance to fix it?

Thanks in advance.

**Comment by ikeydoherty** [comment]
Get it fixed tomorrow for you mate, sorry bout that

**Comment by develop7** [comment]
You rock, man :+1: 

Thanks!

**Comment by develop7** [comment]
Looks like I've managed to fix it (see https://bazaar.launchpad.net/~consort-packagers/consort-panel/quantal-packaging/view/head:/debian/patches/dconf-api-fix.patch)

Drop me a line if you'll decide to adopt this patch. No rush, though — there's clock-applet is waiting to be ported to libgweather v3.x
